import Navbar from "./component/navbar/navbar";
import Providers from "./context/ThemeContext";
import "./globals.css";
import { Poppins } from "next/font/google";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="theme">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
